#!/bin/sh
FIRMAPIUGUI="/usr/bin/firmapiu-gui"
OPTIONS="-Djava.library.path=/usr/lib/jni -classpath /usr/share/java/bcprov.jar:/usr/share/java/bcpkix.jar:/usr/share/java/unix.jar:/usr/share/java/hexdump.jar:/usr/share/java/dbus.jar:/usr/share/java/firmapiud.jar:/usr/share/java/firmapiulib.jar"
FIRMAPIUDAEMON="java $OPTIONS firmapiud.FirmapiuD"
if [ ! -z "$(jps|grep FirmapiuD)" ]
then
	$FIRMAPIUGUI;
else
	$FIRMAPIUDAEMON & 
	sleep 3
	$FIRMAPIUGUI;

fi


