#!/usr/bin/python3

# Copyright (C) 2015 Libersoft <info[at]libersoft[dot]it”

#This file is part of firmapiu-gui.
#
#    firmapiu-gui is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    firmapiu-gui is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with firmapiu-gui.  If not, see <http://www.gnu.org/licenses/>.


__author__ = 'Andrea DellAnna'
import sys
from FirmaPiuGui.PinpukManager import *
if __name__ == '__main__':
    qt_app = QApplication(sys.argv)
    app = PinPukTabDialog()
    app.show()
    # qt_app.exec()
    qt_app.deleteLater()